name: schedule

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Complete App
        run: |
          git config --local user.email "1191430240@qq.com"
          git config --local user.name "ToWeLong"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          go run app.go
          git add .
          git commit -m "update by github action"
          git push
